version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env


  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  nginx:
    image: nginx:1.23
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    ports:
      - "8088:8088"
      - "443:443"




volumes:
  db-data:
  nginx: